In [1]:
import numpy as np
import matplotlib.pyplot as plt
import nglview as nv
import MDAnalysis as mda

In [2]:
from grouping import regroup

In [4]:
list_of_middle = [np.arange(i, i+10) for i in np.arange(1, 90 +1, 10)]

In [5]:
list_of_middle

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40]),
 array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60]),
 array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70]),
 array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90])]

In [6]:
list_of = [i.tolist() for i in list_of_middle]

In [7]:
list_of

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
 [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
 [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
 [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
 [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
 [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]

In [8]:
for_bonds = []
for i in range(len(list_of)):
    if i % 2 == 0:
        for_bonds.append(list_of[i])
    

In [10]:
for_bonds

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
 [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
 [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]]

In [12]:
new_list = []

for i in for_bonds:
    new_list.append(regroup(i))

In [13]:
new_list

[[[1, 2, 3], [3, 4], [4, 5, 6], [6, 7], [7, 8, 9], [9, 10]],
 [[21, 22, 23], [23, 24], [24, 25, 26], [26, 27], [27, 28, 29], [29, 30]],
 [[41, 42, 43], [43, 44], [44, 45, 46], [46, 47], [47, 48, 49], [49, 50]],
 [[61, 62, 63], [63, 64], [64, 65, 66], [66, 67], [67, 68, 69], [69, 70]],
 [[81, 82, 83], [83, 84], [84, 85, 86], [86, 87], [87, 88, 89], [89, 90]]]

In [17]:
from virtual_mass import mass_virtual

In [22]:
from vs import virtual_site1, virtual_site2

In [21]:
virtual_site1(new_list)

2    1    1    3
5    1    4    6
8    1    7    9
22    1    21    23
25    1    24    26
28    1    27    29
42    1    41    43
45    1    44    46
48    1    47    49
62    1    61    63
65    1    64    66
68    1    67    69
82    1    81    83
85    1    84    86
88    1    87    89


In [24]:
from grouping import regroup
virtual_site2(list_of)

NameError: name 'regroup' is not defined

In [26]:
attach = []
for i in list_of:
    attach.append(regroup(i))

In [27]:
attach

[[[1, 2, 3], [3, 4], [4, 5, 6], [6, 7], [7, 8, 9], [9, 10]],
 [[11, 12, 13], [13, 14], [14, 15, 16], [16, 17], [17, 18, 19], [19, 20]],
 [[21, 22, 23], [23, 24], [24, 25, 26], [26, 27], [27, 28, 29], [29, 30]],
 [[31, 32, 33], [33, 34], [34, 35, 36], [36, 37], [37, 38, 39], [39, 40]],
 [[41, 42, 43], [43, 44], [44, 45, 46], [46, 47], [47, 48, 49], [49, 50]],
 [[51, 52, 53], [53, 54], [54, 55, 56], [56, 57], [57, 58, 59], [59, 60]],
 [[61, 62, 63], [63, 64], [64, 65, 66], [66, 67], [67, 68, 69], [69, 70]],
 [[71, 72, 73], [73, 74], [74, 75, 76], [76, 77], [77, 78, 79], [79, 80]],
 [[81, 82, 83], [83, 84], [84, 85, 86], [86, 87], [87, 88, 89], [89, 90]]]

In [28]:
for i in range(len(attach)):
        if i % 2 !=0:
            for j in range(len(attach[i])):
                if j==0: 
                    print(attach[i][j][0],attach[i-1][j][0], attach[i+1][j][0])
                    print(attach[i][j][1], attach[i-1][j][0], attach[i+1][j][-1])
                else:
                    if len(attach[i][j]) == 3: 
                    
                        print(attach[i][j][1],attach[i-1][j][0], attach[i+1][j][-1])
                    elif len(attach[i][j]) == 2:
                        print(attach[i][j][0], attach[i-1][j][0], attach[i+1][j][0])
                        print(attach[i][j][-1], attach[i-1][j][-1], attach[i+1][j][-1])

11 1 21
12 1 23
13 3 23
14 4 24
15 4 26
16 6 26
17 7 27
18 7 29
19 9 29
20 10 30
31 21 41
32 21 43
33 23 43
34 24 44
35 24 46
36 26 46
37 27 47
38 27 49
39 29 49
40 30 50
51 41 61
52 41 63
53 43 63
54 44 64
55 44 66
56 46 66
57 47 67
58 47 69
59 49 69
60 50 70
71 61 81
72 61 83
73 63 83
74 64 84
75 64 86
76 66 86
77 67 87
78 67 89
79 69 89
80 70 90


In [29]:
virtual_site1(new_list)

2    1    1    3
5    1    4    6
8    1    7    9
22    1    21    23
25    1    24    26
28    1    27    29
42    1    41    43
45    1    44    46
48    1    47    49
62    1    61    63
65    1    64    66
68    1    67    69
82    1    81    83
85    1    84    86
88    1    87    89


In [30]:
def virtual_site1(new_list):
    vs1 = []
    for i in range(len(new_list)):
        for j in range(len(new_list[i])):
            if len(new_list[i][j])==3:
                vs1.append([new_list[i][j][1], 1, new_list[i][j][0], new_list[i][j][2]])
    return vs1

In [31]:
def virtual_site2(list_of):
    vs2 = []
    attach = []
    for i in list_of:
        attach.append(regroup(i))
    for i in range(len(attach)):
        if i % 2 !=0:
            for j in range(len(attach[i])):
                if j==0: 
                    vs2.append([attach[i][j][0],1, attach[i-1][j][0], attach[i+1][j][0]])
                    vs2.append([attach[i][j][1],1, attach[i-1][j][0], attach[i+1][j][-1]])
                else:
                    if len(attach[i][j]) == 3: 

                        vs2.append([attach[i][j][1],1,attach[i-1][j][0], attach[i+1][j][-1]])
                    elif len(attach[i][j]) == 2:
                        vs2.append([attach[i][j][0],1, attach[i-1][j][0], attach[i+1][j][0]])
                        vs2.append([attach[i][j][-1],1, attach[i-1][j][-1], attach[i+1][j][-1]])
    return vs2

In [33]:
virtual_site2(list_of)

[[11, 1, 1, 21],
 [12, 1, 1, 23],
 [13, 1, 3, 23],
 [14, 1, 4, 24],
 [15, 1, 4, 26],
 [16, 1, 6, 26],
 [17, 1, 7, 27],
 [18, 1, 7, 29],
 [19, 1, 9, 29],
 [20, 1, 10, 30],
 [31, 1, 21, 41],
 [32, 1, 21, 43],
 [33, 1, 23, 43],
 [34, 1, 24, 44],
 [35, 1, 24, 46],
 [36, 1, 26, 46],
 [37, 1, 27, 47],
 [38, 1, 27, 49],
 [39, 1, 29, 49],
 [40, 1, 30, 50],
 [51, 1, 41, 61],
 [52, 1, 41, 63],
 [53, 1, 43, 63],
 [54, 1, 44, 64],
 [55, 1, 44, 66],
 [56, 1, 46, 66],
 [57, 1, 47, 67],
 [58, 1, 47, 69],
 [59, 1, 49, 69],
 [60, 1, 50, 70],
 [71, 1, 61, 81],
 [72, 1, 61, 83],
 [73, 1, 63, 83],
 [74, 1, 64, 84],
 [75, 1, 64, 86],
 [76, 1, 66, 86],
 [77, 1, 67, 87],
 [78, 1, 67, 89],
 [79, 1, 69, 89],
 [80, 1, 70, 90]]

In [36]:
vs = virtual_site1(new_list) + virtual_site2(list_of)

In [37]:
vs

[[2, 1, 1, 3],
 [5, 1, 4, 6],
 [8, 1, 7, 9],
 [22, 1, 21, 23],
 [25, 1, 24, 26],
 [28, 1, 27, 29],
 [42, 1, 41, 43],
 [45, 1, 44, 46],
 [48, 1, 47, 49],
 [62, 1, 61, 63],
 [65, 1, 64, 66],
 [68, 1, 67, 69],
 [82, 1, 81, 83],
 [85, 1, 84, 86],
 [88, 1, 87, 89],
 [11, 1, 1, 21],
 [12, 1, 1, 23],
 [13, 1, 3, 23],
 [14, 1, 4, 24],
 [15, 1, 4, 26],
 [16, 1, 6, 26],
 [17, 1, 7, 27],
 [18, 1, 7, 29],
 [19, 1, 9, 29],
 [20, 1, 10, 30],
 [31, 1, 21, 41],
 [32, 1, 21, 43],
 [33, 1, 23, 43],
 [34, 1, 24, 44],
 [35, 1, 24, 46],
 [36, 1, 26, 46],
 [37, 1, 27, 47],
 [38, 1, 27, 49],
 [39, 1, 29, 49],
 [40, 1, 30, 50],
 [51, 1, 41, 61],
 [52, 1, 41, 63],
 [53, 1, 43, 63],
 [54, 1, 44, 64],
 [55, 1, 44, 66],
 [56, 1, 46, 66],
 [57, 1, 47, 67],
 [58, 1, 47, 69],
 [59, 1, 49, 69],
 [60, 1, 50, 70],
 [71, 1, 61, 81],
 [72, 1, 61, 83],
 [73, 1, 63, 83],
 [74, 1, 64, 84],
 [75, 1, 64, 86],
 [76, 1, 66, 86],
 [77, 1, 67, 87],
 [78, 1, 67, 89],
 [79, 1, 69, 89],
 [80, 1, 70, 90]]

In [39]:
dc = {}
il = []
for i in list_of:
    for j in i:
        il.append(j)
    for i in il:
        dc[i] = 36
    
    for i in range(len(vs)):
        dc[vs[i][0]] = 0
        
    for i in range(len(vs)):
        for j, k in dc.items():
            if j in vs[i][-2:]:
                dc[j] +=18

In [41]:
print(dc)

{1: 90, 2: 0, 3: 72, 4: 90, 5: 0, 6: 72, 7: 90, 8: 0, 9: 72, 10: 54, 22: 0, 25: 0, 28: 0, 42: 0, 45: 0, 48: 0, 62: 0, 65: 0, 68: 0, 82: 0, 85: 0, 88: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 58: 0, 59: 0, 60: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 21: 108, 23: 108, 24: 108, 26: 108, 27: 108, 29: 108, 30: 72, 41: 108, 43: 108, 44: 108, 46: 108, 47: 108, 49: 108, 50: 72, 61: 108, 63: 108, 64: 108, 66: 108, 67: 108, 69: 108, 70: 72, 81: 72, 83: 90, 84: 72, 86: 90, 87: 72, 89: 90, 90: 54}


In [48]:
np.arange(1,91)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [156]:
with open('graphene.itp', 'w+') as f:
    f.write(";;;;;Graphene\n\n[ moleculetype ]\n; molname nrexcl\n   GRA       1;\n\n[ atoms ]\n; nr type resnr residue atom cgnr charge mass \n")
    for i in np.arange(1,91):
        f.write(f"   {i:4}   TC5   0   GRA   B{i}   {i:4}   {0:4}   {dc[i]:4}\n")
    f.write("\n\n")
    f.write("[ bonds ]\n")
    f.write("; i j funct length kb\n")
    bond_core(new_list, f)
    long_diagonal_bond(new_list,f)
    short_diag_bond(new_list,f)
    side_left(list_of, f)
    side_right(list_of, f)
    f.write("\n\n")
    f.write("#ifndef FLEXIBLE\n")
    f.write("[constraints]\n")
    f.write("#endif\n")
    f.write("; i j funct length \n")
    middle_constraint(new_list,f)
    f.write("\n\n")
    f.write("[ dihedrals ]\n")
    f.write(";  i j k l funct ref.angle force_k\n")
    main_dihedral(new_list,f)
    across_dihedral(new_list,f)
    vertical_diagonal(new_list, f)
    f.write("\n\n")
    f.write("[ virtual_sitesn ]\n")
    f.write("; site funct constructing atom indices\n")
    virtual_site(new_list, list_of, f)
    f.write("\n\n")
    f.write("[ exclusions ]\n")
    exclusions(list_of)
    
    

    

    


 

    

In [72]:
from core_bond import bond_core

ImportError: cannot import name 'bond_core' from 'core_bond' (/home/rshrestha/Desktop/code/ITP_builder/itp_builder/core_bond.py)

In [68]:
core_bond(new_list)

4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324
4    [89, 90]    0.47324


In [59]:
core_i = []
for i in range(len(new_list)):
    for j in new_list[i]:
        if len(j) == 3:
            core_i.append(j[0])

In [60]:
core_i

[1, 4, 7, 21, 24, 27, 41, 44, 47, 61, 64, 67, 81, 84, 87]

In [61]:
core_j = []
for i in range(len(new_list)):
    for j in new_list[i]:
        if len(j) == 3:
            core_j.append(j[-1])

In [62]:
core_j

[3, 6, 9, 23, 26, 29, 43, 46, 49, 63, 66, 69, 83, 86, 89]

In [63]:
len(core_i)

15

In [64]:
len(core_j)

15

In [76]:
for id1, id2 in zip(core_i, core_j):
    print(f"{id1:4}     {id2:4}    {1:4}    {0.47324:4}")

   1        3       1    0.47324
   4        6       1    0.47324
   7        9       1    0.47324
  21       23       1    0.47324
  24       26       1    0.47324
  27       29       1    0.47324
  41       43       1    0.47324
  44       46       1    0.47324
  47       49       1    0.47324
  61       63       1    0.47324
  64       66       1    0.47324
  67       69       1    0.47324
  81       83       1    0.47324
  84       86       1    0.47324
  87       89       1    0.47324


In [95]:
def bond_core(new_list, f):
        core_i = []
        core_j = []
        for i in range(len(new_list)):
            for j in new_list[i]:
                if len(j) == 3:
                    core_i.append(j[0])
                    core_j.append(j[-1])
        for id1, id2 in zip(core_i, core_j):
            f.write(f"{id1:4}     {id2:4}    {1:4}    {0.47324:4}\n")
    

In [91]:
print(bond_core(new_list, 'graphene.itp'))

None


In [97]:
def long_diagonal_bond(new_list, f):
    long_diag_1 = []
    long_diag_2 = []
    for i in range(len(new_list)):
        if i == len(new_list)-1:
            continue
        for j in new_list[i]:
            if len(j) == 3:
                long_diag_1.append(j[0])
            
    for i in range(len(new_list)):
        if i == 0:
            continue
        for j in new_list[i]:
            if len(j) == 2:
                long_diag_2.append(j[0])
                
    for index1, index2 in zip(long_diag_1, long_diag_2):
        f.write(f"{index1:4}    {index2:4}    {1:4}    {0.69393:4}\n")
        
    

In [99]:
def short_diag_bond(new_list, f):
    short_diag_1 = []
    short_diag_2 = []

    for i in range(len(new_list)):
        if i == len(new_list)-1:
            continue
        for j in new_list[i]:
            if len(j) == 2:
                short_diag_1.append(j[0])
            
    for i in range(len(new_list)):
        if i == 0:
            continue
        for j in new_list[i]:
            if len(j) == 2:
                short_diag_2.append(j[-1])
            
    
    for index1, index2 in zip(short_diag_1, short_diag_2):
        f.write(f"{index1:4}    {index2:4}    {1:4}    {0.53627:4}\n")
    

In [103]:
def side_left(list_of, f):
    side_left = []
    for i in range(len(list_of)):
        if i % 2 == 0:
            side_left.append(list_of[i][0])
    sides = [side_left[i:i+2] for i in range(len(side_left)) if len(side_left[i:i+2]) == 2]
    for i in sides:
        f.write(f'{i[0]:4}    {i[-1]:4}    {1:4}    {0.52798:4}\n')

In [105]:
def side_right(list_of, f):
    side_right = []
    for i in range(len(list_of)):
        if i % 2 == 0:
            side_right.append(list_of[i][-1])
    sides = [side_right[i:i+2] for i in range(len(side_right)) if len(side_right[i:i+2]) == 2]
    for i in sides:
        f.write(f'{i[0]:4}    {i[-1]:4}    {1:4}    {0.52798:4}\n')

In [107]:
print(new_list)

[[[1, 2, 3], [3, 4], [4, 5, 6], [6, 7], [7, 8, 9], [9, 10]], [[21, 22, 23], [23, 24], [24, 25, 26], [26, 27], [27, 28, 29], [29, 30]], [[41, 42, 43], [43, 44], [44, 45, 46], [46, 47], [47, 48, 49], [49, 50]], [[61, 62, 63], [63, 64], [64, 65, 66], [66, 67], [67, 68, 69], [69, 70]], [[81, 82, 83], [83, 84], [84, 85, 86], [86, 87], [87, 88, 89], [89, 90]]]


In [108]:
def middle_constraint(new_list, f):
    constraints = []
    for i in new_list:
        for j in i:
            if len(j) == 2:
                constraints.append(j)
    for i in constraints:
        f.write(f"{i[0]:4}    {i[-1]:4}    {1:4}    {0.21170:4}    {1000000:4}\n")
        

In [118]:
def main_dihedral(new_list, f):
    first = []
    second = []
    for i in range(len(new_list)-1):
        for m in new_list[i]:
            if len(m) == 3:
                first.append(m[::-1][0:3:2])
            elif len(m) == 2:
                first.append(m[::-1])
                
    for i in range(1, len(new_list)):
        for m in new_list[i]:
            if len(m) == 3:
                second.append(m[::-1][0:3:2])
            elif len(m) == 2:
                second.append(m[::-1])
                
    for i, j in zip(first, second):
        f.write(f'{i[0]:4}{i[1]:4}{j[0]:4}{j[1]:4}{2:4}{180:4}{400:4}\n')
            

In [115]:
main_dihedral(new_list)

   3   1  23  21   2 180 400
   4   3  24  23   2 180 400
   6   4  26  24   2 180 400
   7   6  27  26   2 180 400
   9   7  29  27   2 180 400
  10   9  30  29   2 180 400
  23  21  43  41   2 180 400
  24  23  44  43   2 180 400
  26  24  46  44   2 180 400
  27  26  47  46   2 180 400
  29  27  49  47   2 180 400
  30  29  50  49   2 180 400
  43  41  63  61   2 180 400
  44  43  64  63   2 180 400
  46  44  66  64   2 180 400
  47  46  67  66   2 180 400
  49  47  69  67   2 180 400
  50  49  70  69   2 180 400
  63  61  83  81   2 180 400
  64  63  84  83   2 180 400
  66  64  86  84   2 180 400
  67  66  87  86   2 180 400
  69  67  89  87   2 180 400
  70  69  90  89   2 180 400


In [120]:
def across_dihedral(new_list, f):
    a_list = []
    b_list = []
    middle1 = []
    middle2 = []
    for i in range(len(new_list)-1):
        for m in new_list[i]:
            if len(m) == 3:
                middle1.append(m[::][0:3:2])
            elif len(m) == 2:
                middle1.append(m[::-1])
    
    for i in range(1, len(new_list)):
        for m in new_list[i]:
            if len(m) == 3:
                middle2.append(m[::-1][0:3:2])
            elif len(m) == 2:
                middle2.append(m[::-1])
    
    
    ab = list(zip(middle1, middle2))
    
    for i in range(len(ab)):
        if i %2 == 0:
            a_list.append([ab[i][0][0], ab[i][1][0]])
        else:
            b_list.append([ab[i][0][1], ab[i][1][0]])
            
            
    for i, j in zip(a_list, b_list):
        f.write(f'{i[0]:4}{i[1]:4}{j[0]:4}{j[1]:4}{2:4}{180:4}{400:4}\n')
    

In [135]:
def vertical_diagonal(new_list, f):
    i = 0
    while i < len(new_list)-2:
        for j in range(len(new_list[i])):
            if len(new_list[i][j]) == 3:
                f.write(f"{new_list[i][j][0]:4}{new_list[i+1][j][::-1][0]:4}{new_list[i+1][j][::-1][1]:4}{new_list[i+2][j][-1]:4}{2:4}{180:4}{400:4}\n")
            elif len(new_list[i][j]) == 2:
                f.write(f"{new_list[i][j][0]:4}{new_list[i+1][j][::-1][0]:4}{new_list[i+1][j][::-1][1]:4}{new_list[i+2][j][-1]:4}{2:4}{180:4}{400:4}\n")
        i = i+1

In [127]:
def vertical_diagonal(new_list):
    i = 0
    while i < len(new_list)-2:
        for j in range(len(new_list[i])):
            if len(new_list[i][j]) == 3:
                print(new_list[i][j][0], *new_list[i+1][j][::-1][0:2], new_list[i+2][j][-1], 2, 180, sep = '    ')
            elif len(new_list[i][j]) == 2:
                print(new_list[i][j][0], *new_list[i+1][j][::-1], new_list[i+2][j][-1], 2, 180, sep = '    ')
        i = i+1

In [128]:
vertical_diagonal(new_list)

1    23    22    43    2    180
3    24    23    44    2    180
4    26    25    46    2    180
6    27    26    47    2    180
7    29    28    49    2    180
9    30    29    50    2    180
21    43    42    63    2    180
23    44    43    64    2    180
24    46    45    66    2    180
26    47    46    67    2    180
27    49    48    69    2    180
29    50    49    70    2    180
41    63    62    83    2    180
43    64    63    84    2    180
44    66    65    86    2    180
46    67    66    87    2    180
47    69    68    89    2    180
49    70    69    90    2    180


In [129]:
def vertical_diagonal(new_list):
    i = 0
    while i < len(new_list)-2:
        for j in range(len(new_list[i])):
            if len(new_list[i][j]) == 3:
                print(new_list[i][j][0], new_list[i+1][j][::-1][0:2][0],new_list[i+1][j][::-1][0:2][1],new_list[i+2][j][-1], 2, 180, sep = '    ')
            elif len(new_list[i][j]) == 2:
                print(new_list[i][j][0], new_list[i+1][j][::-1][0],new_list[i+1][j][::-1][1],new_list[i+2][j][-1], 2, 180, sep = '    ')
        i = i+1

In [130]:
vertical_diagonal(new_list)

1    23    22    43    2    180
3    24    23    44    2    180
4    26    25    46    2    180
6    27    26    47    2    180
7    29    28    49    2    180
9    30    29    50    2    180
21    43    42    63    2    180
23    44    43    64    2    180
24    46    45    66    2    180
26    47    46    67    2    180
27    49    48    69    2    180
29    50    49    70    2    180
41    63    62    83    2    180
43    64    63    84    2    180
44    66    65    86    2    180
46    67    66    87    2    180
47    69    68    89    2    180
49    70    69    90    2    180


In [140]:
virtual_site2(list_of)

[[11, 1, 1, 21],
 [12, 1, 1, 23],
 [13, 1, 3, 23],
 [14, 1, 4, 24],
 [15, 1, 4, 26],
 [16, 1, 6, 26],
 [17, 1, 7, 27],
 [18, 1, 7, 29],
 [19, 1, 9, 29],
 [20, 1, 10, 30],
 [31, 1, 21, 41],
 [32, 1, 21, 43],
 [33, 1, 23, 43],
 [34, 1, 24, 44],
 [35, 1, 24, 46],
 [36, 1, 26, 46],
 [37, 1, 27, 47],
 [38, 1, 27, 49],
 [39, 1, 29, 49],
 [40, 1, 30, 50],
 [51, 1, 41, 61],
 [52, 1, 41, 63],
 [53, 1, 43, 63],
 [54, 1, 44, 64],
 [55, 1, 44, 66],
 [56, 1, 46, 66],
 [57, 1, 47, 67],
 [58, 1, 47, 69],
 [59, 1, 49, 69],
 [60, 1, 50, 70],
 [71, 1, 61, 81],
 [72, 1, 61, 83],
 [73, 1, 63, 83],
 [74, 1, 64, 84],
 [75, 1, 64, 86],
 [76, 1, 66, 86],
 [77, 1, 67, 87],
 [78, 1, 67, 89],
 [79, 1, 69, 89],
 [80, 1, 70, 90]]

In [141]:
def virtual_site(new_list, list_of, f):
    vs = virtual_site1(new_list) + virtual_site2(list_of)
    for i in vs:
        f.write(f"{i[0]:4}{i[1]:4}{i[2]:4}{i[3]:4}\n")

In [149]:
from grouping import regroup
def exclusions(list_of):
    for_excl = []
    for i in list_of:
        for_excl.append(regroup(i))
    for i in range(len(list_of)):
        if i % 2 !=0:
            for j in range(0,len(list_of[i])):
                if j == 0:
                    print(list_of[i][j], list_of[i][j+1], list_of[i-1][j+1], list_of[i-1][j], list_of[i+1][j+1], list_of[i+1][j])
                elif j == len(list_of[i])-1:
                    print(list_of[i][j], list_of[i][j-1],list_of[i-1][j-1], list_of[i-1][j], list_of[i+1][j-1], list_of[i+1][j])
                else:
                    print(list_of[i][j], list_of[i][j+1], list_of[i-1][j], list_of[i-1][j+1],list_of[i+1][j], list_of[i+1][j+1], list_of[i][j-1], list_of[i-1][j-1], list_of[i+1][j-1])
    
    for i in range(len(for_excl)):
        if i == 0:
            for j in range(len(for_excl[i])):
                if len(for_excl[i][j]) == 3:
                    print(for_excl[i][j][1], for_excl[i][j][0], for_excl[i][j][-1], for_excl[i+1][j])
                    
        elif i == len(for_excl) - 1:
            for j in range(len(for_excl[i])):   
                if len(for_excl[i][j]) == 3:
                     print(for_excl[i][j][1], for_excl[i][j][0], for_excl[i][j][-1], for_excl[i-1][j])

In [150]:
exclusions(list_of)

11 12 2 1 22 21
12 13 2 3 22 23 11 1 21
13 14 3 4 23 24 12 2 22
14 15 4 5 24 25 13 3 23
15 16 5 6 25 26 14 4 24
16 17 6 7 26 27 15 5 25
17 18 7 8 27 28 16 6 26
18 19 8 9 28 29 17 7 27
19 20 9 10 29 30 18 8 28
20 19 9 10 29 30
31 32 22 21 42 41
32 33 22 23 42 43 31 21 41
33 34 23 24 43 44 32 22 42
34 35 24 25 44 45 33 23 43
35 36 25 26 45 46 34 24 44
36 37 26 27 46 47 35 25 45
37 38 27 28 47 48 36 26 46
38 39 28 29 48 49 37 27 47
39 40 29 30 49 50 38 28 48
40 39 29 30 49 50
51 52 42 41 62 61
52 53 42 43 62 63 51 41 61
53 54 43 44 63 64 52 42 62
54 55 44 45 64 65 53 43 63
55 56 45 46 65 66 54 44 64
56 57 46 47 66 67 55 45 65
57 58 47 48 67 68 56 46 66
58 59 48 49 68 69 57 47 67
59 60 49 50 69 70 58 48 68
60 59 49 50 69 70
71 72 62 61 82 81
72 73 62 63 82 83 71 61 81
73 74 63 64 83 84 72 62 82
74 75 64 65 84 85 73 63 83
75 76 65 66 85 86 74 64 84
76 77 66 67 86 87 75 65 85
77 78 67 68 87 88 76 66 86
78 79 68 69 88 89 77 67 87
79 80 69 70 89 90 78 68 88
80 79 69 70 89 90
2 1 3 [11, 12, 13]

In [151]:
from grouping import regroup
def exclusions(list_of):
    for_excl = []
    for i in list_of:
        for_excl.append(regroup(i))
    for i in range(len(list_of)):
        if i % 2 !=0:
            for j in range(0,len(list_of[i])):
                if j == 0:
                    f.write(f"{list_of[i][j]}  {list_of[i][j+1]}  {list_of[i-1][j+1]}  {list_of[i-1][j]}  {list_of[i+1][j+1]}  {list_of[i+1][j]}")
                elif j == len(list_of[i])-1:
                    f.write(f"{list_of[i][j]}  {list_of[i][j-1]}  {list_of[i-1][j-1]}  {list_of[i-1][j]}  {list_of[i+1][j-1]}  {list_of[i+1][j]}")
                else:
                    f.write(f"{list_of[i][j]}  {list_of[i][j+1]}  {list_of[i-1][j]}  {list_of[i-1][j+1]}  {list_of[i+1][j]}  {list_of[i+1][j+1]}  {list_of[i][j-1]}  {list_of[i-1][j-1]}  {list_of[i+1][j-1]}")
    
    for i in range(len(for_excl)):
        if i == 0:
            for j in range(len(for_excl[i])):
                if len(for_excl[i][j]) == 3:
                    f.write(f"{for_excl[i][j][1]}  {for_excl[i][j][0]}  {for_excl[i][j][-1]}  {for_excl[i+1][j][0]}  {for_excl[i+1][j][1]}  {for_excl[i+1][j][2]}")
                    
        elif i == len(for_excl) - 1:
            for j in range(len(for_excl[i])):   
                if len(for_excl[i][j]) == 3:
                     f.write(f"{for_excl[i][j][1]}  {for_excl[i][j][0]}  {for_excl[i][j][-1]}  {for_excl[i-1][j][0]:2}  {for_excl[i-1][j][1]:2} {for_excl[i-1][j][2]:2}")

In [154]:
from grouping import regroup
def exclusions(list_of):
    for_excl = []
    for i in list_of:
        for_excl.append(regroup(i))
    for i in range(len(list_of)):
        if i % 2 !=0:
            for j in range(0,len(list_of[i])):
                if j == 0:
                    f.write(f"{list_of[i][j]}  {list_of[i][j+1]}  {list_of[i-1][j+1]}  {list_of[i-1][j]}  {list_of[i+1][j+1]}  {list_of[i+1][j]}\n")
                elif j == len(list_of[i])-1:
                    f.write(f"{list_of[i][j]}  {list_of[i][j-1]}  {list_of[i-1][j-1]}  {list_of[i-1][j]}  {list_of[i+1][j-1]}  {list_of[i+1][j]}\n")
                else:
                    f.write(f"{list_of[i][j]}  {list_of[i][j+1]}  {list_of[i-1][j]}  {list_of[i-1][j+1]}  {list_of[i+1][j]}  {list_of[i+1][j+1]}  {list_of[i][j-1]}  {list_of[i-1][j-1]}  {list_of[i+1][j-1]}\n")
    
    for i in range(len(for_excl)):
        if i == 0:
            for j in range(len(for_excl[i])):
                if len(for_excl[i][j]) == 3:
                    f.write(f"{for_excl[i][j][1]}  {for_excl[i][j][0]}  {for_excl[i][j][-1]}  {for_excl[i+1][j][0]}  {for_excl[i+1][j][1]}  {for_excl[i+1][j][2]}\n")
                    
        elif i == len(for_excl) - 1:
            for j in range(len(for_excl[i])):   
                if len(for_excl[i][j]) == 3:
                     f.write(f"{for_excl[i][j][1]}  {for_excl[i][j][0]}  {for_excl[i][j][-1]}  {for_excl[i-1][j][0]:2}  {for_excl[i-1][j][1]:2} {for_excl[i-1][j][2]:2}\n")